name: Deploy Vite App

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20 # You can specify the Node.js version you need

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist # Specify the directory where your Vite app is built
          publish_branch: master # Change this to your target branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
